server:
  port: 8080
spring:
  redis:
    port: 6379
    database: 1
    host: 127.0.0.1
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
